# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Coffee(object):
    def setupUi(self, Coffee):
        Coffee.setObjectName("Coffee")
        Coffee.resize(600, 600)
        Coffee.setMinimumSize(QtCore.QSize(0, 0))
        Coffee.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.centralwidget = QtWidgets.QWidget(parent=Coffee)
        self.centralwidget.setObjectName("centralwidget")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 0, 584, 451))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(280, 470, 311, 61))
        self.pushButton.setObjectName("pushButton")
        Coffee.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Coffee)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 21))
        self.menubar.setObjectName("menubar")
        Coffee.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=Coffee)
        self.statusbar.setObjectName("statusbar")
        Coffee.setStatusBar(self.statusbar)

        self.retranslateUi(Coffee)
        QtCore.QMetaObject.connectSlotsByName(Coffee)

    def retranslateUi(self, Coffee):
        _translate = QtCore.QCoreApplication.translate
        Coffee.setWindowTitle(_translate("Coffee", "MainWindow"))
        self.pushButton.setText(_translate("Coffee", "Добавить запись о кофе или изменить существующую"))
